INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Adam Reynolds', N'Broncos Brisbane', N'Halfback', 32, 173, 85)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Brian To''o', N'Panthers', N'Winger', 24, 182, 97)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Corey Oates', N'Broncos Brisbane', N'Winger', 28, 192, 105)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Deine Mariner', N'Broncos Brisbane', N'Centre', NULL, NULL, NULL)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Delouise Hoeter', N'Broncos Brisbane', N'Centre', 29, 185, 92)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Dylan Edwards', N'Panthers', N'Fullback', 27, 183, 94)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Ethan Quai-Ward', N'Broncos Brisbane', N'Centre', 23, 96, 190)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Ezra Mam', N'Broncos Brisbane', N'Five-Eighth', 20, 176, 85)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Herbie Farnworth', N'Broncos Brisbane', N'Centre', 23, 190, 106)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Izack Tago', N'Panthers', N'Centre', 21, 184, 93)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Jack Cogger', N'Panthers', N'Five-Eighth', 25, 175, 90)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Jarome Luai', N'Panthers', N'Five-Eighth', 26, 184, 90)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Jock Madden', N'Broncos Brisbane', N'Halfback', 23, 180, 82)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Nathan Cleary', N'Panthers', N'Captain - Halfback', 25, 182, 92)
INSERT INTO [dbo].[Players] ([PlayerName], [TeamName], [Position], [Age], [Height], [Weight]) VALUES (N'Stephen Crichton', N'Panthers', N'Centre', 22, 193, 99)
