//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRL_Ladder_FrontEnd_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ladder
    {
        public string SeasonID { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Drawn { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> Byes { get; set; }
        public Nullable<int> For { get; set; }
        public Nullable<int> Against { get; set; }
        public Nullable<int> Differential { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
    }
}
