//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRL_Ladder_FrontEnd_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string PlayerName { get; set; }
        public string TeamName { get; set; }
        public string Position { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
